### ISSUE TITLE
Voting / Consolidate ?

### ISSUE THREAD

**Issue by JoshuaJBerk** [cjbarber/ToolsOfTheTrade#109]
HN voting was a strong signal, but it's missing here -- also, each category really should be limited to a small # of services, or else this becomes less valuable.

**Comment by limist** [comment]
+1

**Comment by davisonio** [comment]
I think at the moment the sections are fine - most of the sections are less than twenty services. When choosing a service, although this may seem like a lot, I think it's good to have a selection of services at different price ranges because it definitely depends on the organisation that you are in.

As for votes, I'm not too sure and it's something we might have to put forward for discussion. If there's a service which is having a very negative reputation / is unpopular amongst the people on Hacker News then we may consider removing it. After all, this is a list of great services for people to enjoy.

I've recently cleared some of the defunct services so hopefully that should reduce the changes of ending up on a dysfunctional link :)
