### ISSUE TITLE
Not all listed tools are hosted

### ISSUE THREAD

**Issue by webmaven** [cjbarber/ToolsOfTheTrade#121]
Some of the tools listed are self-hosted. Should these be removed as contradicting the expressed purpose of the list?

**Comment by davisonio** [comment]
This is actually a very good point, the original purpose of the two Hacker News threads. I'll leave this issue open here so we can go through this list, looking at services that don't offer hosting.

**Comment by webmaven** [comment]
So, any further thoughts or progress?

**Comment by davisonio** [comment]
I've decided that due to the fact there are quite a few services that are self-hosted only, or those that other both hosted and self-hosted services we will keep self-hosted tools here. I think the scope of the list has expanded.

From now onwards, tags should be added to the end of items using `Hosted`, `Self-hosted` or both. This will give everyone a great idea about how the tool can be used without having to dig round on their website :)

https://github.com/cjbarber/ToolsOfTheTrade/commit/bc3296bc1dcde1917e33b2866cb65df97de26892
